In [2]:
import pandas as pd
import requests

In [7]:
requests.get('https://aerodatabox.p.rapidapi.com/health/services/feeds/FlightSchedules/airports')

In [6]:
response = requests.get('https://aerodatabox.p.rapidapi.com/health/services/feeds/FlightSchedules/airports')

In [8]:
response.json()

{'message': 'Invalid API key. Go to https://docs.rapidapi.com/docs/keys for more info.'}

In [13]:
import requests

url = "https://aerodatabox.p.rapidapi.com/airports/iata/DME"

headers = {
	"X-RapidAPI-Key": "1400d8f71dmsha12222371ce4d06p16c339jsnff0f8c9a8dcc",
	"X-RapidAPI-Host": "aerodatabox.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers)

response.json()['icao']

'UUDD'

In [3]:
data=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=c5bc87518260a2911807fb0ab754193d&language=en-US&page=1')

In [4]:
data

In [5]:
data.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 44.097,
   'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
   'release_date': '1995-10-19',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.7,
   'vote_count': 3761},
  {'adult': False,
   'backdrop_path': '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 88.892,
   'poster_path': '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.7,
   'vote_count': 21974},
  {'adult': False,
   'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 104.396,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.7,
   'vote_count': 16361},
  {'adult': False,
   'backdrop_path': '/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 49.84,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.6,
   'vote_count': 13029},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather: Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 65.084,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather: Part II',
   'video': False,
   'vote_average': 8.6,
   'vote_count': 9863},
  {'adult': False,
   'backdrop_path': '/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg',
   'genre_ids': [10751, 18],
   'id': 667257,
   'original_language': 'es',
   'original_title': 'Cosas imposibles',
   'overview': 'Matilde is a woman who, after the death of her husband - a man who constantly abused her - finds her new best friend in Miguel, her young, insecure, disoriented and even dealer neighbor',
   'popularity': 22.484,
   'poster_path': '/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg',
   'release_date': '2021-06-17',
   'title': 'Impossible Things',
   'video': False,
   'vote_average': 8.6,
   'vote_count': 260},
  {'adult': False,
   'backdrop_path': '/iQlJyRecJeGGzQGT2rEcyAgz89F.jpg',
   'genre_ids': [10749, 18],
   'id': 762975,
   'original_language': 'en',
   'original_title': 'Purple Hearts',
   'overview': 'An aspiring musician agrees to a marriage of convenience with a soon-to-deploy Marine, but a tragedy soon turns their fake relationship all too real.',
   'popularity': 1568.566,
   'poster_path': '/4JyNWkryifWbWXJyxcWh3pVya6N.jpg',
   'release_date': '2022-07-29',
   'title': 'Purple Hearts',
   'video': False,
   'vote_average': 8.6,
   'vote_count': 987},
  {'adult': False,
   'backdrop_path': '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 90.723,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 13175},
  {'adult': False,
   'backdrop_path': '/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg',
   'genre_ids': [10749, 16],
   'id': 372754,
   'original_language': 'ja',
   'original_title': '同級生',
   'overview': 'Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.',
   'popularity': 12.707,
   'poster_path': '/cIfRCA5wEvj9tApca4UDUagQEiM.jpg',
   'release_date': '2016-02-20',
   'title': 'Dou kyu sei – Classmates',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 241},
  {'adult': False,
   'backdrop_path': '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
   'genre_ids': [10749, 16, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 134.505,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 8953},
  {'adult': False,
   'backdrop_path': '/v5CEt88iDsuoMaW1Q5Msu9UZdEt.jpg',
   'genre_ids': [10749, 18],
   'id': 730154,
   'original_language': 'ja',
   'original_title': 'きみの瞳が問いかけている',
   'overview': "A tragic accident lead to Kaori's blindness, but she clings to life and the smaller pleasures it can still afford her. She meets Rui and begins to talk to him. Rui was once a promising kickboxer, but something happened in his past. Kaori's smile brings out a change in Rui. However, the two are connected in more than one way. Rui attempts to do what is right.",
   'popularity': 45.046,
   'poster_path': '/cVn8E3Fxbi8HzYYtaSfsblYC4gl.jpg',
   'release_date': '2020-10-23',
   'title': 'Your Eyes Tell',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 342},
  {'adult': False,
   'backdrop_path': '/tj6iPnz18hGfr0LKqWmG6Cp3niO.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 34.654,
   'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 6581},
  {'adult': False,
   'backdrop_path': '/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg',
   'genre_ids': [10749],
   'id': 696374,
   'original_language': 'en',
   'original_title': "Gabriel's Inferno",
   'overview': "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
   'popularity': 12.156,
   'poster_path': '/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg',
   'release_date': '2020-05-29',
   'title': "Gabriel's Inferno",
   'video': False,
   'vote_average': 8.5,
   'vote_count': 2263},
  {'adult': False,
   'backdrop_path': '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 72.901,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 14143},
  {'adult': False,
   'backdrop_path': '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 73.735,
   'poster_path': '/velWPhVMQeQKcxggNEU8YmIo52R.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 14245},
  {'adult': False,
   'backdrop_path': '/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg',
   'genre_ids': [10749],
   'id': 724089,
   'original_language': 'en',
   'original_title': "Gabriel's Inferno: Part II",
   'overview': "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
   'popularity': 13.33,
   'poster_path': '/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg',
   'release_date': '2020-07-31',
   'title': "Gabriel's Inferno: Part II",
   'video': False,
   'vote_average': 8.5,
   'vote_count': 1421},
  {'adult': False,
   'backdrop_path': '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
   'genre_ids': [18, 28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 83.042,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-14',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 28031},
  {'adult': False,
   'backdrop_path': '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 48.756,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-23',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 6786},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 83.45,
   'poster_path': '/fIE3lAGcZDV1G6XM5KmuWnNsPp1.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 23591},
  {'adult': False,
   'backdrop_path': '/pm0RiwNpSja8gR0BTWpxo5a9Bbl.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
   'popularity': 112.342,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-01',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 19957}],
 'total_pages': 511,
 'total_results': 10206}

In [6]:
import pandas
import requests

In [8]:
response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=c5bc87518260a2911807fb0ab754193d&language=en-US&page=1')

In [22]:
temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [23]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-19,44.097,8.7,3761
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,88.892,8.7,21974
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,104.396,8.7,16361
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,49.840,8.6,13029
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,1974-12-20,65.084,8.6,9863
5,667257,Impossible Things,"Matilde is a woman who, after the death of her...",2021-06-17,22.484,8.6,260
6,762975,Purple Hearts,An aspiring musician agrees to a marriage of c...,2022-07-29,1568.566,8.6,987
7,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,90.723,8.5,13175
8,372754,Dou kyu sei – Classmates,"Rihito Sajo, an honor student with a perfect s...",2016-02-20,12.707,8.5,241
9,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,134.505,8.5,8953
10,730154,Your Eyes Tell,"A tragic accident lead to Kaori's blindness, b...",2020-10-23,45.046,8.5,342
11,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,34.654,8.5,6581
12,696374,Gabriel's Inferno,An intriguing and sinful exploration of seduct...,2020-05-29,12.156,8.5,2263
13,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,72.901,8.5,14143
14,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,73.735,8.5,14245
15,724089,Gabriel's Inferno: Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,13.330,8.5,1421
16,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-14,83.042,8.5,28031
17,429,"The Good, the Bad and the Ugly","While the Civil War rages on, three men – a qu...",1966-12-23,48.756,8.5,6786
18,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,83.450,8.5,23591
19,122,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,2003-12-01,112.342,8.5,19957

In [24]:
df=pd.DataFrame()

In [25]:
df

Empty DataFrame
Columns: []
Index: []

In [30]:
for i in range (1,5):
    response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=c5bc87518260a2911807fb0ab754193d&language=en-US&page={}'.format(i))
    temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df=df.append(temp_df,ignore_index=True)

C:\Users\mrsud\AppData\Local\Temp\ipykernel_7812\1290007807.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(temp_df,ignore_index=True)
C:\Users\mrsud\AppData\Local\Temp\ipykernel_7812\1290007807.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(temp_df,ignore_index=True)
C:\Users\mrsud\AppData\Local\Temp\ipykernel_7812\1290007807.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(temp_df,ignore_index=True)
C:\Users\mrsud\AppData\Local\Temp\ipykernel_7812\1290007807.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(temp_df,ignore_index=True)

In [31]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-19,44.097,8.7,3761
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,88.892,8.7,21974
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,104.396,8.7,16361
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,49.840,8.6,13029
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,1974-12-20,65.084,8.6,9863
...,...,...,...,...,...,...,...
10155,618344,Justice League Dark: Apokolips War,Earth is decimated after intergalactic tyrant ...,2020-05-05,47.462,8.3,1197
10156,105,Back to the Future,Eighties teenager Marty McFly is accidentally ...,1985-07-03,60.757,8.3,16837
10157,975,Paths of Glory,A commanding officer defends three scapegoats ...,1957-10-25,16.047,8.3,2244
10158,15804,A Brighter Summer Day,"A boy experiences first love, friendships and ...",1991-07-27,11.850,8.3,201
10159,447362,Life in a Year,A 17 year old finds out that his girlfriend is...,2020-11-27,79.439,8.3,1123

In [32]:
df.shape

(10160, 7)

In [33]:
df.to_csv('movies.csv')

In [1]:
import pandas as pd

In [13]:
df=pd.read_csv("C:/Users/mrsud/Documents/Python code/counties.csv")

In [14]:
df

,fips,country,state,county,level,lat,locationId,long,population,metrics.testPositivityRatio,...,actuals.hsaIcuBeds.capacity,actuals.hsaIcuBeds.currentUsageTotal,actuals.hsaIcuBeds.currentUsageCovid,metrics.bedsWithCovidPatientsRatio,hsaName,actuals.hospitalBeds.weeklyCovidAdmissions,actuals.hsaHospitalBeds.weeklyCovidAdmissions,metrics.weeklyCovidAdmissionsPer100k,communityLevels.cdcCommunityLevel,communityLevels.canCommunityLevel
0,2013,US,AK,Aleutians East Borough,county,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,3337,0.162,...,95.0,81.0,7.0,0.045,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,60.0,13.0,2.0,2.0
1,2016,US,AK,Aleutians West Census Area,county,NaN,iso1:us#iso2:us-ak#fips:02016,NaN,5634,0.050,...,95.0,81.0,7.0,0.045,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,60.0,13.0,1.0,1.0
2,2020,US,AK,Anchorage Municipality,county,NaN,iso1:us#iso2:us-ak#fips:02020,NaN,288000,0.207,...,95.0,81.0,7.0,0.045,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",42.0,60.0,13.0,2.0,2.0
3,2050,US,AK,Bethel Census Area,county,NaN,iso1:us#iso2:us-ak#fips:02050,NaN,18386,0.091,...,95.0,81.0,7.0,0.045,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,60.0,13.0,2.0,2.0
4,2060,US,AK,Bristol Bay Borough,county,NaN,iso1:us#iso2:us-ak#fips:02060,NaN,836,0.111,...,95.0,81.0,7.0,0.045,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,60.0,13.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3218,56037,US,WY,Sweetwater County,county,NaN,iso1:us#iso2:us-wy#fips:56037,NaN,42343,0.199,...,8.0,3.0,0.0,0.022,"Sweetwater, WY - Daggett, UT",5.0,5.0,13.9,1.0,1.0
3219,56039,US,WY,Teton County,county,NaN,iso1:us#iso2:us-wy#fips:56039,NaN,23464,0.194,...,10.0,1.0,0.0,0.013,"Teton, WY - Lincoln, WY",5.0,5.0,9.4,1.0,1.0
3220,56041,US,WY,Uinta County,county,NaN,iso1:us#iso2:us-wy#fips:56041,NaN,20226,0.083,...,6.0,0.0,0.0,0.000,"Uinta, WY",4.0,4.0,0.0,0.0,0.0
3221,56043,US,WY,Washakie County,county,NaN,iso1:us#iso2:us-wy#fips:56043,NaN,7805,0.058,...,13.0,4.0,0.0,0.016,"Fremont, WY - Washakie, WY",4.0,7.0,11.7,1.0,1.0
3222,56045,US,WY,Weston County,county,NaN,iso1:us#iso2:us-wy#fips:56045,NaN,6927,0.273,...,NaN,NaN,NaN,0.024,"Weston, WY",4.0,4.0,28.9,2.0,2.0

In [16]:
df=pd.read_csv('C:\\Users\\mrsud\\Documents\\Python code\\counties.csv')

In [17]:
df

,fips,country,state,county,level,lat,locationId,long,population,metrics.testPositivityRatio,...,actuals.hsaIcuBeds.capacity,actuals.hsaIcuBeds.currentUsageTotal,actuals.hsaIcuBeds.currentUsageCovid,metrics.bedsWithCovidPatientsRatio,hsaName,actuals.hospitalBeds.weeklyCovidAdmissions,actuals.hsaHospitalBeds.weeklyCovidAdmissions,metrics.weeklyCovidAdmissionsPer100k,communityLevels.cdcCommunityLevel,communityLevels.canCommunityLevel
0,2013,US,AK,Aleutians East Borough,county,NaN,iso1:us#iso2:us-ak#fips:02013,NaN,3337,0.162,...,95.0,81.0,7.0,0.045,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,60.0,13.0,2.0,2.0
1,2016,US,AK,Aleutians West Census Area,county,NaN,iso1:us#iso2:us-ak#fips:02016,NaN,5634,0.050,...,95.0,81.0,7.0,0.045,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,60.0,13.0,1.0,1.0
2,2020,US,AK,Anchorage Municipality,county,NaN,iso1:us#iso2:us-ak#fips:02020,NaN,288000,0.207,...,95.0,81.0,7.0,0.045,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",42.0,60.0,13.0,2.0,2.0
3,2050,US,AK,Bethel Census Area,county,NaN,iso1:us#iso2:us-ak#fips:02050,NaN,18386,0.091,...,95.0,81.0,7.0,0.045,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,60.0,13.0,2.0,2.0
4,2060,US,AK,Bristol Bay Borough,county,NaN,iso1:us#iso2:us-ak#fips:02060,NaN,836,0.111,...,95.0,81.0,7.0,0.045,"Anchorage (Anchorage), AK - Matanuska-Susitna ...",NaN,60.0,13.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3218,56037,US,WY,Sweetwater County,county,NaN,iso1:us#iso2:us-wy#fips:56037,NaN,42343,0.199,...,8.0,3.0,0.0,0.022,"Sweetwater, WY - Daggett, UT",5.0,5.0,13.9,1.0,1.0
3219,56039,US,WY,Teton County,county,NaN,iso1:us#iso2:us-wy#fips:56039,NaN,23464,0.194,...,10.0,1.0,0.0,0.013,"Teton, WY - Lincoln, WY",5.0,5.0,9.4,1.0,1.0
3220,56041,US,WY,Uinta County,county,NaN,iso1:us#iso2:us-wy#fips:56041,NaN,20226,0.083,...,6.0,0.0,0.0,0.000,"Uinta, WY",4.0,4.0,0.0,0.0,0.0
3221,56043,US,WY,Washakie County,county,NaN,iso1:us#iso2:us-wy#fips:56043,NaN,7805,0.058,...,13.0,4.0,0.0,0.016,"Fremont, WY - Washakie, WY",4.0,7.0,11.7,1.0,1.0
3222,56045,US,WY,Weston County,county,NaN,iso1:us#iso2:us-wy#fips:56045,NaN,6927,0.273,...,NaN,NaN,NaN,0.024,"Weston, WY",4.0,4.0,28.9,2.0,2.0

In [18]:
df['popularity'].max()

KeyError: 'popularity'

In [19]:
df['population'].max()

10039107

In [20]:
df['population'][df['population']=='18386']

Series([], Name: population, dtype: int64)

In [26]:
df['population'][df['population']==18386]

3      18386
387    18386
Name: population, dtype: int64

In [ ]:
df=pd.read_csv('')